### ISSUE TITLE
File name on disk does not change

### ISSUE THREAD

**Issue by tespheakdeyesoftix** [DataJuggler/BlazorFileUpload#1]
Hi,
I try to use this to upload file in my blazor project server side and every thing work good except file name store on disk does not change. 
I already set this property AppendPartialGuid = "true" but still not work.
Any advise suggestion?

Thanks

**Comment by DataJuggler** [comment]
I added a couple of features since I added AppendPartialGuid and it seems the AppendPartialGuid doesn't work, but the file still saved without the Guid being appended.

Dot Net Core 3.1 comes out this week so I am planning a new update already. Did you try running the FileUpload Sample in this project? I just tested and it works, although the Guid is missing. I will create an issue for this when I get off work.

Sorry

**Comment by DataJuggler** [comment]
I wasn't ready to start working yet. I fixed the issue. I wasn't setting NameWithPartialGuid correctly.

I am updating the Nuget package also, so in a few minutes it should work.

Thank you for testing and finding this.

Let me know if this works and I will close this issue after you get the latest code.

Corby

**Comment by tespheakdeyesoftix** [comment]
Thank for your information.  
I will update in my project and let you know asap.

Thank you very much
Pheakdey

**Comment by tespheakdeyesoftix** [comment]
Hi Corby,

yes, it works now. 
Thank you very much.

Pheakdey

**Comment by DataJuggler** [comment]
Thanks for letting me know about the issue.
